apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
  name: acm-console-link
spec:
  applicationMenu:
    imageURL: 'https://multicloud-console.apps.ocp4.ray-hklab.com/multicloud/favicon.svg'
    section: Red Hat Applications
  href: 'https://multicloud-console.apps.ocp4.ray-hklab.com'
  location: ApplicationMenu
  text: Not Applicable
