apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: codeready
spec:
  href: 'https://codeready-openshift-workspaces.apps.ocp4.ray-hklab.com/dashboard/'
  location: ApplicationMenu
  text: CodeReady Workspaces
  applicationMenu:
    section: Red Hat applications
    imageURL: https://avatars.githubusercontent.com/u/56974?s=200&v=4
